name: Cypress Test
on:
  push:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm ci
    - run: npm apt-get install -y google-chrome-stable
    - run: google-chrome --version
    - name: Run Cypress tests
      run: npx cypress run browser chrome
    - uses: actions/upload-artifact@v2
